import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from 'react'
import '@rainbow-me/rainbowkit/styles.css';
import ClientComponent from "@/component/ClientComponent";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientComponent>
          {children}
        </ClientComponent> {/* 使用客户端组件 */}
      </body>
    </html>
  );
}